version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-android-sdk
    container_name: jenkins_android_31
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
    driver: local
